name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/prepare

    - run: pnpm lint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        vite-version: [^2.5.10, ^3.0.0, ^4.0.0, ^5.0.0, ^6.0.0, ^7.0.0]

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/prepare

    - run: pnpm add -D vite@${{ matrix.vite-version }}
    - run: pnpm test
